/**
 *
 * @author Brandon Kong and Dylan Chang
 * Date: 01/13/2020
 * File Name: MainMenu_jFrame
 * Description: A jFrame that displays the main menu with 
 * JButtons that allow users to start different difficulties of
 * Sudoku games, check the rules of the game, or check highscores.
 */

package SudokuGame;


import static SudokuGame.Soduko.getDifficulty;
import static SudokuGame.Soduko.setDifficulty;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;


public class MainMenu_jFrame extends javax.swing.JFrame {

    /**
     * Creates new form test_jframe
     */
    public MainMenu_jFrame(){
        initComponents();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Easy_But = new javax.swing.JButton();
        Medium_But = new javax.swing.JButton();
        Hard_But = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(874, 508));
        setPreferredSize(new java.awt.Dimension(110, 63));
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));
        getContentPane().setLayout(null);

        Easy_But.setFont(new java.awt.Font("Bradley Hand ITC", 0, 24)); // NOI18N
        Easy_But.setText("Easy");
        Easy_But.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Easy_ButActionPerformed(evt);
            }
        });
        getContentPane().add(Easy_But);
        Easy_But.setBounds(350, 180, 180, 50);

        Medium_But.setFont(new java.awt.Font("Bradley Hand ITC", 0, 24)); // NOI18N
        Medium_But.setText("Medium");
        Medium_But.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Medium_ButActionPerformed(evt);
            }
        });
        getContentPane().add(Medium_But);
        Medium_But.setBounds(350, 230, 180, 50);

        Hard_But.setFont(new java.awt.Font("Bradley Hand ITC", 0, 24)); // NOI18N
        Hard_But.setText("Hard");
        Hard_But.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Hard_ButActionPerformed(evt);
            }
        });
        getContentPane().add(Hard_But);
        Hard_But.setBounds(350, 280, 180, 50);

        jButton1.setFont(new java.awt.Font("Bradley Hand ITC", 0, 24)); // NOI18N
        jButton1.setText("Rules");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(350, 330, 180, 60);

        jButton2.setFont(new java.awt.Font("Bradley Hand ITC", 0, 24)); // NOI18N
        jButton2.setText("High Scores");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(300, 390, 300, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SudokuGame/SudokuRESIZE.png"))); // NOI18N
        jLabel2.setMinimumSize(new java.awt.Dimension(1280, 920));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, -300, 860, 1080);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void Easy_ButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Easy_ButActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        setDifficulty(1);
        new SudokuBoard_jFrame().setVisible(true);
    }//GEN-LAST:event_Easy_ButActionPerformed

    private void Medium_ButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Medium_ButActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        setDifficulty(2);
        new SudokuBoard_jFrame().setVisible(true);
    }//GEN-LAST:event_Medium_ButActionPerformed

    private void Hard_ButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Hard_ButActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        setDifficulty(3);
        new SudokuBoard_jFrame().setVisible(true);
    }//GEN-LAST:event_Hard_ButActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new Rules_jFrame().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new tableTesting().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed


    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu_jFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu_jFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu_jFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu_jFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu_jFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Easy_But;
    private javax.swing.JButton Hard_But;
    private javax.swing.JButton Medium_But;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
